# Generated by Django 5.2 on 2025-04-30 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default_name', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'AssetCategory',
                'verbose_name_plural': 'AssetCategories',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('AssetId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='default_name', max_length=100, unique=True)),
                ('Shortname', models.CharField(max_length=50, unique=True)),
                ('Description', models.CharField(blank=True, max_length=200)),
                ('Unit', models.CharField(max_length=50, null=True)),
                ('AssetCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.assetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDetails',
            fields=[
                ('Sn', models.AutoField(primary_key=True, serialize=False)),
                ('AssetCode', models.CharField(max_length=50, unique=True)),
                ('Price', models.FloatField()),
                ('PurchaseDate', models.DateField()),
                ('Remarks', models.CharField(blank=True, max_length=200)),
                ('Status', models.CharField(choices=[('working', 'Working'), ('not_working', 'Not Working'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('in_repair', 'In Repair'), ('disposed', 'Disposed')], default='Working', max_length=50)),
                ('Asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
            ],
            options={
                'verbose_name': 'AssetDetails',
                'verbose_name_plural': 'AssetDetails',
            },
        ),
        migrations.CreateModel(
            name='AssetOut',
            fields=[
                ('Sn', models.AutoField(primary_key=True, serialize=False)),
                ('Outdate', models.DateField()),
                ('DateToReturn', models.DateField()),
                ('ReturnDate', models.DateField()),
                ('Remarks', models.CharField(blank=True, max_length=200)),
                ('AssetDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.assetdetails')),
                ('OutTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AssetOut',
                'verbose_name_plural': 'AssetOut',
            },
        ),
    ]
