# Generated by Django 5.2 on 2025-04-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'AssetCategory', 'verbose_name_plural': 'AssetCategories'},
        ),
        migrations.AlterModelOptions(
            name='assetdetails',
            options={'verbose_name': 'AssetDetails', 'verbose_name_plural': 'AssetDetails'},
        ),
        migrations.AlterModelOptions(
            name='assetout',
            options={'verbose_name': 'AssetOut', 'verbose_name_plural': 'AssetOut'},
        ),
    ]
