# Generated by Django 5.2 on 2025-05-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='Description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
