# Generated by Django 5.2 on 2025-04-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_asset_options_alter_assetdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'AssetCategory', 'verbose_name_plural': 'AssetCategory'},
        ),
    ]
