# Generated by Django 5.2 on 2025-05-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_asset_description_alter_asset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdetails',
            name='Status',
            field=models.CharField(choices=[('working', 'Working'), ('not_working', 'Not Working'), ('available', 'Available'), ('not_available', 'Not Available'), ('in_use', 'In Use'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('in_repair', 'In Repair'), ('disposed', 'Disposed')], default='Working', max_length=50),
        ),
    ]
