# Generated by Django 5.2 on 2025-05-07 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_assetdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='Unit',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
