# Generated by Django 5.2 on 2025-04-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_asset_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'verbose_name': 'AssetCategory', 'verbose_name_plural': 'AssetCategories'},
        ),
    ]
